apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ibou
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-ibou@sha256:5070528a845cf1ca34274289dc8330c27ef2cdb63914682fc6d4a83e5fb71bdb
        name: my-nodejs
        resources: {}
status: {}
